### ISSUE TITLE
load picker with selected icon in case of edit 

### ISSUE THREAD

**Issue by gerendo** [micc83/fontIconPicker#38] opened 2017-12-20 11:20 UTC
hi guys , i just inform you that i add simple code .briefly  I add in your picker 
a part That allow to initialize with a selected icon already 

[jquery.fonticonpicker.zip](https://github.com/micc83/fontIconPicker/files/1575301/jquery.fonticonpicker.zip)
the function which i add called "this.setSelectedIcon" line 879

**Comment by swashata** [comment] 2018-03-21 05:51
I am closing this because the issue isn't explaining the problem and the solution. Please feel free to reopen with needed examples and explanation of what you are trying to achieve.

**Closed by swashata** 2018-03-21 05:51 UTC
